language: go

go:
  - "1.13.x"

env:
  - GOLANGCI_RELEASE="v1.23.6"

before_install:
  - export PATH=$PATH:$GOPATH/bin
  - curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | bash -s ${GOLANGCI_RELEASE}

script:
  - golangci-lint run --tests --disable-all --enable=goimports --enable=golint --enable=govet --enable=errcheck --enable=staticcheck
  - go test -v -covermode=count
