language: go

go:
  - "1.10.x"
  - "1.11.x"
  - "1.12.x"
  - "1.13.x"

env:
  - GOLANGCI_RELEASE="v1.15.0"

before_install:
  - export PATH=$PATH:$GOPATH/bin
  - curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin ${GOLANGCI_RELEASE}

script:
  - golangci-lint run --tests --disable-all --enable=goimports --enable=golint --enable=govet --enable=errcheck --enable=staticcheck
  - go test -v -covermode=count
