language: go

go:
  - "1.13.x"

env:
  - GOLANGCI_RELEASE="v1.23.6"

before_install:
  - export PATH=$PATH:$GOPATH/bin
  - curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | bash -s ${GOLANGCI_RELEASE}

script:
  - env GO111MODULE=on make lint
  - env GO111MODULE=on make test
